Adds info log line to trace when a lock release times out
sky-uk/cqlmigrate pull request #95
Opened 2021-04-13 13:11 UTC by fdayamanisky

Co-authored-by: Joshua Jones <joshua.jones@sky.uk>

2021-04-27 12:28 UTC, chuckydev approved these changes

2021-05-05 15:04 UTC, fincefid requested changes
Can you also rebase it from the master please?

2021-05-05 15:04 UTC, fincefid commented on src/main/java/uk/sky/cqlmigrate/CassandraLockingMechanism.java
> +            log.info("Lock release timed out for client {}", clientId);
I think we should make that warning rather than info. A similar case can be found in the **acquire** method

2021-05-18 08:11 UTC, davidh87 commented
@fdayamanisky is this still needed?

2021-05-18 08:43 UTC, fdayamanisky commented
This was done while I was on boomerang to Lakitu. @blondgitninja or someone else currently in the team would be better placed to answer

2021-12-17 09:12 UTC, adamdougal commented
I'm going to close this. If it's still needed please rebase and reopen. Thanks.

2021-12-17 09:12 UTC, closed without merging